# Generated by Django 3.2.2 on 2021-05-08 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('cinema_id', models.AutoField(primary_key=True, serialize=False)),
                ('cinema_name', models.CharField(max_length=32, unique=True)),
            ],
            options={
                'verbose_name': 'cinema',
            },
        ),
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('hall_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('cinema_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.user')),
            ],
            options={
                'verbose_name': 'hall',
            },
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'comment'},
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('schedule_id', models.AutoField(primary_key=True, serialize=False)),
                ('show_date', models.DateTimeField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('seat_info', models.TextField()),
                ('hall_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.hall')),
                ('movie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.movie')),
            ],
            options={
                'verbose_name': 'schedule',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_seat_info', models.CharField(max_length=100)),
                ('pay_type', models.IntegerField(choices=[(1, '支付宝'), (2, '微信')], default=1)),
                ('schedule_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.schedule')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.user')),
            ],
            options={
                'verbose_name': 'order',
            },
        ),
    ]
